#!/bin/bash
. play-head
cd ..
./play-download	|| exit 1
./play-binutils	|| exit 1
./play-gccp1	|| exit 1
./play-dietlibc	|| exit 1
./play-gccp2	|| exit 1
echo 'export PATH='$PREFIX'/bin:$PATH' > crossenv
echo DONE
