#!/bin/bash
. play-head
function xget () {
	if [ ! -f $1 ]; then
		wget $2/$1
	fi
}

function die() {
	echo Error:$1
	exit 1
}

mkdir -p pkg
cd pkg
echo '----Download package----'
xget $BINUTILS.tar.bz2 $MIRROR/binutils || die 'binutils'
xget $GCC.tar.xz $MIRROR/gcc/$GCC || die 'gcc'
xget $GMP.tar.bz2 $MIRROR/gmp || die 'gmp'
xget $MPFR.tar.bz2 $MIRROR/mpfr || die 'mpfr'
xget $MPC.tar.gz $MIRROR/mpc || die 'mpc'
cd ..
if [ ! -d $DIETLIBC ]; then
	git clone https://github.com/hchunhui/dietlibc.git $DIETLIBC || die 'dietlibc'
fi
echo '----Done----'

